// src/routes/about/+page.svelte
<h2 class="text-2xl font-bold leading-loose">Me</h2>
<p class="leading-relaxed">我叫 <span class="underline">“浅小沫”</span>，你可以叫我：小沫、<b>小白</b>！英文 ID 是 “Truimo”，已经不太清楚这个 ID 是怎么来的了...</p>
<h3 class="text-lg font-semibold leading-loose">- Contact</h3>
<p class="leading-relaxed">电子邮件: <a href="mailto:i@truimo.com">i@truimo.com</a></p>
<h2 class="text-2xl font-bold leading-loose">Domain</h2>
<p class="leading-relaxed">当然是英文 ID 加 com 作为域名啦，好像没有别的特色了。</p>
<div class="h-10"></div>
<p class="leading-relaxed">最后，很高兴遇见你！</p>
<p class="leading-relaxed">总之，你好。</p>

// src/app/about/page.tsx

export default function Page() {
    return (
        <div>
            <h2 className="text-2xl font-bold leading-loose">Me</h2>
            <p className="leading-relaxed">我叫 <span className="underline">“浅小沫”</span>，你可以叫我：小沫、<b>小白</b>！英文 ID 是 “Truimo”，已经不太清楚这个 ID 是怎么来的了...</p>
            <h3 className="text-lg font-semibold leading-loose">- Contact</h3>
            <p className="leading-relaxed">电子邮件: <a href="mailto:i@truimo.com">i@truimo.com</a></p>
            <h2 className="text-2xl font-bold leading-loose">Domain</h2>
            <p className="leading-relaxed">当然是英文 ID 加 com 作为域名啦，好像没有别的特色了。</p>
            <div className="h-10"></div>
            <p className="leading-relaxed">最后，很高兴遇见你！</p>
            <p className="leading-relaxed">总之，你好。</p>
        </div>
    )
}
