// src/components/layout/footer/Footer.tsx
import {icp, owner} from '@/config'

export const Footer = () => {
    return (
        <footer>
            <div className="h-16 max-w-6xl mx-auto flex justify-center items-center">
                <p className="text-center text-sm text-zinc-500">Copyright&nbsp;&copy;&nbsp;2018-2025&nbsp;<a href="/">{owner.name}</a>.&nbsp;<a>Home</a>.&nbsp;
                    {icp && (<a href={icp.link} rel="nofollow noreferrer" target="_blank">{icp.text}</a>)}</p>
            </div>
        </footer>
    )
}

// src/components/Footer.svelte
<footer>
    <div class="h-16 max-w-6xl mx-auto flex justify-center items-center">
        <p class="text-center text-sm text-zinc-500">
            <span>Copyright&nbsp;&copy;&nbsp;2018-2024&nbsp;<a href="/">Truimo's Home</a>.&nbsp;</span>
            <a href="http://beian.miit.gov.cn/" rel="nofollow noreferrer" target="_blank">湘ICP备2020021033号-1</a>
        </p>
    </div>
</footer>
